# Site settings
title: Praqma
email: info@praqma.com
phone: +45 36772 762
logo: /images/logo.png
description: The Continuous Delivery Company
slogan: — In Praqma we strive to change the world…
url: http://new.praqma.com #TODO replace with http://praqma.com

# Build settings
markdown: kramdown

#sass:
  #sourcemap: :true
style: debug

permalink: /:categories/:title/

collections:
  tag-pages:
    output: true
    permalink: /blog/:path/
  training:
    output: true
    permalink: /training/:path/

defaults:
  -
    scope:
      path: "" # any file
    values:
      layout: page
  -
    scope:
      type: posts
    values:
      categories: blog
      layout: post
  -
    scope:
      type: tag-pages
    values:
      categories: [tag-page, blog] #it goes into body classes and impacts on styles
      #categories: tag-page
      #permalink: pretty
      layout: tag-page
  -
    scope:
      type: training
    values:
      layout: training-page
