# Site settings
title: Praqma
email: info@praqma.net
logo: /images/logo.png
description: The Continuous Delivery Company
slogan: — In Praqma we strive to change the world…
url: http://praqma.com
permalink: none

# Build settings
markdown: kramdown

sass:
  #sass_dir: bower_components/bootstrap-sass/assets/stylesheets

defaults:
  -
    scope:
      path: "" # any file
    values:
      layout: page
  -
    scope:
      type: post
    values:
      #permalink: /blog/:name/
      #title: hello #why works to all pages?
      categories: blog
  -
    scope:
      path: pages/tags
    values:
      #permalink: /blog/:name/
      #title: hello #why works to all pages?
      categories: [tag-page, blog]
      layout: tag-page
