# Site settings
title: Praqma
email: info@praqma.com
phone: +45 36772 762
logo: /images/logo.png
description: The Continuous Delivery and DevOps Company
slogan: — In Praqma we strive to change the world…
url: http://new.praqma.com #TODO replace with http://praqma.com
stories:
  default-tag: Featured

# Only use gems that are supported by github
# the gems must be installed on your local system to support jekyll build/serve
# Example
#    $ gem install jekyll-redirect-from
gems:
  - jekyll-redirect-from

# Build settings
markdown: kramdown

#sass:
  #sourcemap: :true
style: debug

permalink: /:categories/:title/

collections:
  training:
    output: true
    permalink: /training/:path/
  services:
    output: true
    permalink: /services/:path/
  about-pages:
    output: true
    permalink: /about/:path/

defaults:
  -
    scope:
      path: "" # any file
    values:
      layout: page
  -
    scope:
      type: posts
    values:
      categories: stories
      layout: post
      weight: 0
  -
    scope:
      type: training
    values:
      layout: training-page
  -
    scope:
      type: services
    values:
      layout: service-page
  -
    scope:
      type: about-pages
    values:
      layout: about-page
